### ISSUE TITLE
Peer review 1

### ISSUE THREAD

**Issue by HeljaeRaeisaenen** [JHNUL/quizmaster#33]
In short, I think the app is looking great and doing great! I couldn’t find any bugs or weirdness, so I’m just going to list a bunch of nitpicks that came to mind.

- When testing the app, I created a user called 'helloo' in the system. It appears as if my user had created the quizzes already in the app when I logged in, which I as a user think is confusing, since I did not make the quizzes.
![image](https://user-images.githubusercontent.com/94612974/229606153-bf6a4e6f-73d7-4d59-9dcc-519bf22d691c.png)

- I think it would be nice to display the time it took to finsih the quiz (finish time minus start time) since the start and finish times are already shown.
- In the quiz creation page, it’s not clear what the checkboxes do. There could be more instructions for the user. I assume they mark wich answer is correct.
- It seems to be possible to create a quiz with all incorrect answer options. I think this is funny in a good way and I don’t know if it’s a flaw, just wanted to let you know / remind you.
- To me, the DB tables *quiz_question* and *question_answer* look redundant, why not put the quiz_id inside the ‘question’ table, and question_id inside ‘answer’ table? I may just not understand the DB relations correctly however.

Good stuff:

- Good that you can’t change the selected answer by going back a page
- The visual style is good
- The repository, documentation etc. looks very good
- I cannot find any flaws or issues in your code
- You obviously are much more experienced than I am :D

**Comment by JHNUL** [comment]
Thanks for the comments!

> When testing the app, I created a user called 'helloo' in the system. It appears as if my user had created the quizzes already in the app when I logged in, which I as a user think is confusing, since I did not make the quizzes.

This is indeed a bug! Thanks for reporting it :)

> To me, the DB tables quiz_question and question_answer look redundant, why not put the quiz_id inside the ‘question’ table, and question_id inside ‘answer’ table? I may just not understand the DB relations correctly however.

Yeah, I originally went with a loose coupling between quiz/question and question/answer so the same question in theory could be used in multiple quizzes and the same answer in multiple questions. If e.g. question table held quiz_id it would not be possible to link the same question to multiple quizzes. But I'm sure this kind of "reusing questions" logic won't be implemented in this project, so I might at some point drop the connection tables for simplicity.

Good points about the UX and usability, I will for sure add them to todos (some are there already). As for not requiring any answer option to be correct, that was on purpose :D Similarly all answer options can be correct.
